# Tensors

In [3]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [4]:
import torch

In [5]:
t = torch.Tensor(dd)

In [6]:
type(t)

torch.Tensor

### Shape

In [9]:
# Shape basically tells us about the no. of indices we got for the axeses
t.shape

torch.Size([3, 3])

In [11]:
# Rank - len() of the shape
len(t.shape)
# so we requires two indices

2

### Reshape

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [13]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [14]:
t = t.reshape(1,9)

In [15]:
t

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

### Tensor creation operations

In [16]:
import numpy as np

In [17]:
data = np.array([1,2,3])

In [18]:
t = torch.Tensor(data)

In [19]:
torch.tensor(data)

tensor([1, 2, 3])

In [20]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [22]:
torch.from_numpy(data)

tensor([1, 2, 3])

### Tensor creation without the data

In [23]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [24]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.rand(2,3)

tensor([[0.9768, 0.9192, 0.9189],
        [0.2220, 0.2388, 0.1929]])

### Reshaping of the tensors- more detailed version

In [27]:
import torch
import numpy as np

In [29]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [30]:
t.size()

torch.Size([3, 4])

In [31]:
t.shape

torch.Size([3, 4])

In [32]:
len(t.shape)

2

In [33]:
# To know about the scalar component of tensors
torch.tensor(t.shape).prod()

tensor(12)

In [36]:
# Short Form for number of element
t.numel()

12

#### Squeeze and Unsqueezing to change the rank of the tensor

In [38]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [39]:
# squeezing leads to flattening of the tensors
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [40]:
# While the unsqueezing leads to adding up more dimensions to the rank
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


#### Flatten

In [41]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

## Reduction Operation


###### Reduction opn reduces the number of element contained in the tensor

### Argmax opn

In [42]:
import torch
import numpy as np

In [43]:
t = torch.tensor([
    [1,0,1],
    [0,2,0],
    [3,0,3]
],dtype = torch.float32)

In [48]:
t.sum()


tensor(10.)

####  First example for the reduction operation
#### Result is the scalar value tensor

In [45]:
t.numel()

9

In [46]:
t.sum().numel()


1

In [47]:
t.sum().numel() < t.numel()

True

#### All the following methods reduces the tensor to single value element

In [50]:
print(t.std())
print(t.mean())
print(t.prod())

tensor(1.2693)
tensor(1.1111)
tensor(0.)
