# Tensors

In [3]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [4]:
import torch

In [5]:
t = torch.Tensor(dd)

In [6]:
type(t)

torch.Tensor

### Shape

In [9]:
# Shape basically tells us about the no. of indices we got for the axeses
t.shape

torch.Size([3, 3])

In [11]:
# Rank - len() of the shape
len(t.shape)
# so we requires two indices

2

### Reshape

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [13]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [14]:
t = t.reshape(1,9)

In [15]:
t

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

### Tensor creation operations

In [16]:
import numpy as np

In [17]:
data = np.array([1,2,3])

In [18]:
t = torch.Tensor(data)

In [19]:
torch.tensor(data)

tensor([1, 2, 3])

In [20]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [22]:
torch.from_numpy(data)

tensor([1, 2, 3])

### Tensor creation without the data

In [23]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [24]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.rand(2,3)

tensor([[0.9768, 0.9192, 0.9189],
        [0.2220, 0.2388, 0.1929]])